travis:
  secure:
    BINSTAR_TOKEN: a6KFraRsIJL9/AsSuHLSp97zUodUCdLQHCvCAC+SVlF9LM8hkuGX/RVqGMDI1cVwQd1bo+9Iq1UQ6t5mvWmOBjCZRmcGcJAA2pU4QL5MT5eBIHGai6sVYf13Gu1/CFH2nEco5WdFCCFMYxARkEscz+/9S1V5s0R4TbwTH7VP7BuyuVZRSJGzdbMyIspOCgIpbJWRctA/5LmnD96j2sGUxXeGqOprZMoWLigTtqBlITk6586Oad/S48gAJiyNRKDOuU0C5foYx8yOPmYYZyivRGz7WPZqcB1ci2Yk1X7awazGPONV2BWGnUSO6fsgLvzpTEqw4WhmUNSC3kdT9a57yWsxFeOv/PF8vnAXl/H76XOTpIzHBYEp17B7d+NhulO8Da9WPZ4KZ/gPc5ms3x7O6dWNp2WaCfuXlhOqhpDnj57Wz7s+SFyS5BXf6b2vcHpBtpbZTAHR/PGFDReP2ah7xzb3QWSqj+Opx9NkOeKSxYsyFnVDLMrJeXP5/SyScFPx57WNJWJnAquRW31jIYqFIbU0IROhhaUouf0zqzds7s5kYRVoMunpDNrVTt71W9OjsKsxFxb0byz9Ndi7DS17XPYRWds6tQ83nCmnUamnbUjleYmgC9yFEC6MNL0ZGG3JxhzxU7pJfo/2pnsL7yMXm4QYjXupSCVimWR2xNb+X0M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
